sudo: required

services:
- docker

language: node_js
node_js:
- '6'

before_install:
- docker-compose build --no-cache

script:
- npm test
- docker-compose run --rm jackal_client sh -c "sleep 2 && ./test/docker/docker_test_commands.sh"

after_success:
- npm run coveralls
- bash ./docker_publish.sh

deploy:
  provider: npm
  email: spanners@findmypast.com
  api_key:
    secure: g+hsKfFwtFh2zuGTE8l/tS9BVk1SOPC9gfAfKPd9qHCQLG7tvVqN2FaHAzRK9zdUFBrBH8HqtiPu37iWEeygt7N1CGtRGGBYCkZsrfoAI00Q55SFDpWMoSqBbpiAjqlIT54z/MgAt3OnwxPJ5CID5rvaUUiMITB2XcSOQ7+BkNE/sPiYvAeZogdCFFFpNr//cT5k5NqeeCPmq282twGhEwroHl4Iv/fJdN+R0EgY9luccpQjgSzmX2fEmJeUz1AghJ9riCq6Z0YIuUo7IoyMvxia9IvSJ4skRxnRLE0dpKpBZIcJhjBCJSi0ior252bm0dJWQCTBIDc7ZcEWZZhQ5QgscQHDC4reUQvU111dyPbp+XyIldUt45Bdyqtp9YgKqC+mGn7HOyJkAlYBDlFRxWCH3lIyAoNsdnytUSaNyDv0A3iTtzEqd69SXjFBlzm4Bf2i14qP/jZq+3XGkJAdzhW/KVf6syzaCKWnc/++mj6rNxXEFDkhngV8fubzkttDvk+4rDg6gFAe+yCKFLELECH0F2btEfFnQDSNLut1TWHLh/4fw414lt1B/2pTsXZRLA8jNzR+wXH9KQqI8AYbbMvPliVrPqDmZAdF3uhK7gKYmKLKzwkAOZwld6wjy57+AGKhHHqkj5RkU3IWIJtWuu59b16ZoccGOGitp1tDtSs=
  on:
    tags: true
    repo: findmypast-oss/jackal

notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: cTuJYnheMrE8LN3wtG9OPJo93W+aJeQqikCDoDleqanbtsYCqh+miN1OHSI/sWhkNNbLTU0oEEXeFlrxbgAzdBOhX+0tsYix/HIsRCCjqUkonhXmW6qsSnYq/XKbvAHORUhaeGN0AZeXqi3mJJiAp25TsD+xqXkEbP8ka4ayQigfkTiDgeFOfDBC64QhgHV4PImoa6bBH/TzSu0f3IHB+/s9JfJRcw32+DlHpLgBuWj5hvdf6DGA9nfK4GsdmPpV4GwewSTp2uwUF+Ucr6QkLeZuQEuKHCLpcUk3c4Lanbnu1WGd2ARCfdZYuybYvgw39OmYlNEI/7f9TCyrZJcHJUUNAy9BOktD4L5UslYvrmM9563GZFXtXooBf+OR+7lPA3qjxZNA5CrKDZ7SwEOgAR5o8FIclRKoHd32NJ4E5ZCGpmTQrFKdE58cJkKlydCNs5O+YrLLLCq/2BcZ77wNFZ3+YhLmXQ7wVT0tZDsfmlv2Sa16zFp8x2hq/7AxNwtMRlkT6o5K9dH2T/YzNiJlMPL88tPYHWEKXSNtjsB26VEpKha0OYTZjarUzsgM3oUQvy/+pexGjWhCfXADV8ygSyv1v/lAcxHUmIymcsMUeD2OLZutv/wHI/cG2Bjy1sgnehRvLG5FLBCDfV3q6E0aLg1xikISt6y07CdUgzwEeuU=
