jackal:
  baseUrl: 'http://jackal'
  port: 25863
logger:
  environment: development
stats: {}
provider: {}
statsD:
  host: localhost
  port: 8125
  prefix: jackal
db:
  path: db.json
reporters:
  pretty: true
  teamcity: false
quiet: true
